---
- name: Enable and start nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Check nginx config and restart
  block:
    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      register: nginx_test
      ignore_errors: true

    - name: Fail if Nginx config test failed
      ansible.builtin.fail:
        msg: "Nginx configuration test failed! Check the config."
      when: nginx_test.rc != 0

    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
