---
- name: Check if fullchain exists
  ansible.builtin.stat:
    path: "{{ nginx_fullchain_path }}"
  register: fullchain_stat

- name: Check if private key exists
  ansible.builtin.stat:
    path: "{{ nginx_private_key_path }}"
  register: privkey_stat

- name: Ensure web root exists
  ansible.builtin.file:
    path: "{{ nginx_web_root_path }}"
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"
    mode: "0755"
