---
- import_playbook: ../install-sing-box/playbook.yml
- name: "ansiblecfgs: wireguard-sing-box"
  hosts: all
  become: true
  tasks:
    - name: Deploy WireGuard nftables rules
      block:
        - name: Copy WireGuard nftables snippet
          template:
            src: "20-wireguard-sb.nft.j2"
            dest: /etc/nftables.d/20-wireguard-sb.nft
            mode: "0644"

        - name: Reload nftables rules
          command: nft -f /etc/nftables.conf

    - name: Install wireguard
      apt:
        name:
          - wireguard
        state: present
        update_cache: yes
      register: apt_result
      until: apt_result is succeeded
      retries: 10
      delay: 15

    - name: Generate WireGuard keys with sing-box
      block:
        - name: Generate server keys
          command: sing-box generate wg-keypair
          register: server_keys

        - name: Set server key facts
          set_fact:
            wg_server_private_key: "{{ server_keys.stdout.split('PrivateKey: ')[1].split()[0] }}"
            wg_server_public_key: "{{ server_keys.stdout.split('PublicKey: ')[1].split()[0] }}"

        - name: Print server keys
          debug:
            msg:
              - "ATTENTION! Server keys:"
              - "PrivateKey: {{ wg_server_private_key }}"
              - "PublicKey: {{ wg_server_public_key }}"
              - "You need to copy PublicKey into the client's config."

        - name: Generate client keys
          command: sing-box generate wg-keypair
          register: client_keys

        - name: Set client key facts
          set_fact:
            wg_client_private_key: "{{ client_keys.stdout.split('PrivateKey: ')[1].split()[0] }}"
            wg_client_public_key: "{{ client_keys.stdout.split('PublicKey: ')[1].split()[0] }}"

        - name: Print client keys
          debug:
            msg:
              - "ATTENTION! Client keys:"
              - "PrivateKey: {{ wg_client_private_key }}"
              - "PublicKey: {{ wg_client_public_key }}"
              - "You need to copy the private key into the client config."

    - name: Deploy sing-box server config
      template:
        src: sing-box-server.json.j2
        dest: /etc/sing-box/config.json
        mode: "0644"

    - name: Enable and start sing-box
      systemd:
        name: sing-box
        enabled: true
        state: started

    - name: Reboot server
      reboot:
        reboot_timeout: 3
