---
- name: "ansiblecfgs: wireguard-sing-box"
  hosts: all
  become: true

  pre_tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - name: Upgrade all packages
      apt:
        upgrade: dist
      register: apt_upgrade
      until: apt_upgrade is succeeded
      retries: 10
      delay: 15

    - name: Gather installed packages
      ansible.builtin.package_facts:
        manager: auto

    - name: Deploy WireGuard nftables rules
      block:
        - name: Copy WireGuard nftables snippet
          template:
            src: "20-wireguard-sb.nft.j2"
            dest: /etc/nftables.d/20-wireguard-sb.nft
            mode: "0644"

        - name: Reload nftables rules
          command: nft -f /etc/nftables.conf

    - name: Add SagerNet repo and key
      block:
        - name: Ensure keyrings dir
          file:
            path: /etc/apt/keyrings
            state: directory
            mode: "0755"

        - name: Download GPG key
          get_url:
            url: https://sing-box.app/gpg.key
            dest: /etc/apt/keyrings/sagernet.asc
            mode: "0644"

        - name: Add APT source
          copy:
            dest: /etc/apt/sources.list.d/sagernet.sources
            content: |
              Types: deb
              URIs: https://deb.sagernet.org/
              Suites: *
              Components: *
              Enabled: yes
              Signed-By: /etc/apt/keyrings/sagernet.asc
            mode: "0644"

    - name: Install sing-box and wireguard
      apt:
        name:
          - wireguard
          - sing-box
        state: present
        update_cache: yes
      register: sagernet_install
      until: sagernet_install is succeeded
      retries: 10
      delay: 15

    - name: Generate WireGuard keys with sing-box
      block:
        - name: Generate server keys
          command: sing-box generate wg-keypair
          register: server_keys

        - name: Set server key facts
          set_fact:
            wg_server_private_key: "{{ server_keys.stdout.split('PrivateKey: ')[1].split()[0] }}"
            wg_server_public_key: "{{ server_keys.stdout.split('PublicKey: ')[1].split()[0] }}"

        - name: Print server keys
          debug:
            msg:
              - "ATTENTION! Server keys:"
              - "PrivateKey: {{ wg_server_private_key }}"
              - "PublicKey: {{ wg_server_public_key }}"
              - "You need to copy PublicKey into the client's config."

        - name: Generate client keys
          command: sing-box generate wg-keypair
          register: client_keys

        - name: Set client key facts
          set_fact:
            wg_client_private_key: "{{ client_keys.stdout.split('PrivateKey: ')[1].split()[0] }}"
            wg_client_public_key: "{{ client_keys.stdout.split('PublicKey: ')[1].split()[0] }}"

        - name: Print client keys
          debug:
            msg:
              - "ATTENTION! Client keys:"
              - "PrivateKey: {{ wg_client_private_key }}"
              - "PublicKey: {{ wg_client_public_key }}"
              - "You need to copy the private key into the client config."

    - name: Deploy sing-box server config
      template:
        src: sing-box-server.json.j2
        dest: /etc/sing-box/config.json
        mode: "0644"

    - name: Enable and start sing-box
      systemd:
        name: sing-box
        enabled: true
        state: started

    - name: Reboot server
      reboot:
        reboot_timeout: 3
