---
- name: "lego: install"
  hosts: all
  become: true
  tasks:
    - name: "lego: install"
      ansible.builtin.include_role:
        name: lego
        tasks_from: install.yml

    - name: "lego: explicit start"
      ansible.builtin.include_role:
        name: lego
        tasks_from: explicit_start.yml
