---
- name: "lego: render reload script"
  hosts: all
  become: true
  tasks:
    - name: "Export vars"
      block:
        - name: "caddy: export vars"
          ansible.builtin.include_role:
            name: caddy
            tasks_from: export_vars.yml

        - name: "sing-box: export vars"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: export_vars.yml

    - name: "lego: copy hooks"
      ansible.builtin.include_role:
        name: lego
        tasks_from: copy_hooks.yml
      vars:
        lego_hooks:
          - path: "{{ caddy_reload_script }}"
            name: caddy.sh
          - path: "{{ singbox_reload_script }}"
            name: singbox.sh

    - name: "lego: explicit start"
      ansible.builtin.include_role:
        name: lego
        tasks_from: explicit_start.yml
