---
- name: "include: install Docker"
  ansible.builtin.import_playbook: ../docker/install.yml

- name: "include: firewall allow HTTP"
  ansible.builtin.import_playbook: ../firewall/allow_http.yml

- name: "ghost: install"
  hosts: all
  become: true
  tasks:
    - name: "Export vars"
      block:
        - name: "lego: export vars"
          ansible.builtin.include_role:
            name: lego
            tasks_from: export_vars.yml

        - name: "ghost: export vars"
          ansible.builtin.include_role:
            name: ghost
            tasks_from: export_vars.yml

        - name: "caddy: export vars"
          ansible.builtin.include_role:
            name: caddy
            tasks_from: export_vars.yml

    - name: "Set vars"
      ansible.builtin.set_fact:
        caddy_certificates: "{{ lego_certificates_dir }}"
        caddy_ghost_domain: "{{ ghost_domain }}"
        caddy_ghost_admin_domain: "{{ ghost_admin_domain }}"
        caddy_ghost_reverse_proxy: "ghost:{{ ghost_port }}"

    - name: "ghost: install"
      ansible.builtin.include_role:
        name: ghost
        tasks_from: install.yml

    - name: "lego: install"
      ansible.builtin.include_role:
        name: lego
        tasks_from: install.yml

    - name: "caddy: install"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: install.yml

    - name: "caddy: install ghost"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: install_ghost.yml

    - name: "lego: explicit start"
      ansible.builtin.include_role:
        name: lego
        tasks_from: explicit_start.yml

    - name: "lego: copy hooks"
      ansible.builtin.include_role:
        name: lego
        tasks_from: copy_hooks.yml
      vars:
        lego_hooks:
          - path: "{{ caddy_reload_script }}"
            name: caddy.sh

    - name: "caddy: rebuild"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: rebuild.yml
