---
- name: Enable and start Caddy
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started

- name: Check Caddy config and reload
  block:
    - name: Test Caddy configuration
      ansible.builtin.command: caddy validate --config /etc/caddy/Caddyfile
      register: caddy_test
      ignore_errors: true

    - name: Fail if Caddy config test failed
      ansible.builtin.fail:
        msg: "Caddy configuration test failed! Check the Caddyfile."
      when: caddy_test.rc != 0

    - name: Reload Caddy service
      ansible.builtin.systemd:
        name: caddy
        state: reloaded
        enabled: true
