---
- name: Ensure domain dir exists
  ansible.builtin.file:
    path: "{{ caddy_webroot_dir }}/{{ item.domain }}"
    state: directory
    owner: "{{ caddy_system_user }}"
    group: "{{ caddy_system_group }}"
    mode: "0755"
  loop: "{{ caddy_sites }}"
  loop_control:
    label: "{{ item.domain }}"
  when: item.domain is defined and item.domain | length > 0

- name: Render Caddy site configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ caddy_configs_dir }}/{{ item.domain }}.caddyfile"
    owner: "{{ caddy_system_user }}"
    group: "{{ caddy_system_group }}"
    mode: "0644"
  loop: "{{ caddy_sites }}"
  loop_control:
    label: "{{ item.domain }}"
  when: item.src is defined and item.src | length > 0 and item.domain is defined and item.domain | length > 0

- name: Remove Caddy site configs if not needed
  ansible.builtin.file:
    path: "{{ caddy_configs_dir }}/{{ item.domain }}.caddyfile"
    state: absent
  loop: "{{ caddy_sites }}"
  loop_control:
    label: "{{ item.domain }}"
  when: item.domain is defined and (item.src is not defined or item.src | length == 0)
