---
- name: Set default Caddy configuration
  ansible.builtin.set_fact:
    caddy_dockerfile: "{{ caddy_dockerfile | default('caddy.Dockerfile', true) }}"
    caddy_configs: "{{ caddy_configs | default(caddy_configs_default, true) }}"

- name: Create Caddy directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    group: "{{ docker_group }}"
    mode: "0755"
  loop:
    - "{{ caddy_dir }}"
    - "{{ caddy_sites_dir }}"
    - "{{ caddy_file_server }}"
    - "{{ caddy_data }}"

- name: Render Compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ caddy_compose }}"
    mode: "0644"

- name: Copy Caddy Dockerfile
  ansible.builtin.copy:
    src: "{{ caddy_dockerfile }}"
    dest: "{{ caddy_image }}"

- name: Render reload script
  ansible.builtin.template:
    src: reload.sh.j2
    dest: "{{ caddy_reload_script }}"
    mode: "0755"

- include_tasks: rebuild.yml

- include_tasks: deploy_configs.yml

- name: Copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: "{{ caddy_file_server }}/index.html"
