---
- name: Set default Caddy configuration
  ansible.builtin.set_fact:
    caddy_dockerfile: "{{ caddy_dockerfile | default('naive.Dockerfile', true) }}"
    caddy_configs: "{{ caddy_configs | default(caddy_configs_default_naive, true) }}"

- include_tasks: install.yml
