---
- include_tasks: https_check.yml

- name: Copy HTML file
  ansible.builtin.copy:
    src: reality_sfy.html
    dest: "{{ caddy_webroot_path }}/index.html"
    owner: "{{ caddy_user | default('caddy') }}"
    group: "{{ caddy_user | default('caddy') }}"
    mode: "0755"

- name: Generate Caddy site config
  ansible.builtin.template:
    src: reality_sfy.caddyfile.j2
    dest: "/etc/caddy/conf.d/{{ caddy_domain }}.caddyfile"
    owner: root
    group: root
    mode: "0644"
