---
- include_tasks: https_check.yml

- name: Copy HTML file
  ansible.builtin.copy:
    src: reality_sfy.html
    dest: "{{ caddy_domain_dir }}/index.html"
    owner: "{{ caddy_system_user }}"
    group: "{{ caddy_system_group }}"
    mode: "0755"

- name: Generate Caddy site config
  ansible.builtin.template:
    src: reality_sfy.caddyfile.j2
    dest: "{{ caddy_configs_dir }}/{{ caddy_domain }}.caddyfile"
    owner: root
    group: root
    mode: "0644"
