---
# download_xray_locally | install_xray
xray_local_temp_dir: "{{ role_path }}/xray_temp"

# download_xray_locally
xray_url: "https://github.com/XTLS/Xray-core/releases/download/v26.3.27/Xray-linux-arm64-v8a.zip"
# optional
xray_sha256: "4d30283ae614e3057f730f67cd088a42be6fdf91f8639d82cb69e48cde80413c"

# download_singbox_locally | install_singbox
singbox_local_temp_dir: "{{ role_path }}/singbox_temp"

# download_singbox_locally
singbox_url: "https://github.com/SagerNet/sing-box/releases/download/v1.14.0-alpha.44/sing-box-1.14.0-alpha.44-linux-arm64-musl.tar.gz"
# optional
singbox_sha256: "03ea34e62030151aaa0988f54573548f74a979f323f5fdbc77e00f64d759651a"

# install_xray
xray_local_files: "{{ role_path }}/files/install_xray"

xray_tproxy_port: 3000
xray_confdir: ""
xray_asset: "/usr/local/share/xray"

xray_bin: "/usr/local/bin/xray"
xray_local_bin: "{{ xray_local_temp_dir }}/xray"

xray_uci: "/etc/config/xray"
xray_local_uci: "{{ xray_local_temp_dir }}/uci"

xray_init: "/etc/init.d/xray"
xray_local_init: "{{ xray_local_temp_dir }}/init"

xray_config: "{{ xray_asset }}/config.json"
xray_local_config: "{{ xray_local_temp_dir }}/config.json"

xray_geosite: "{{ xray_asset }}/geosite.dat"
xray_local_geosite: "{{ xray_local_files }}/geosite.dat"

xray_geoip: "{{ xray_asset }}/geoip.dat"
xray_local_geoip: "{{ xray_local_files }}/geoip.dat"

# install_singbox
singbox_local_files: "{{ role_path }}/install_singbox"

singbox_bin: "/usr/local/bin/sing-box"
singbox_local_bin: "{{ singbox_local_temp_dir }}/sing-box"

singbox_uci: "/etc/config/sing-box"
singbox_local_uci: "{{ singbox_local_temp_dir }}/uci"

singbox_init: "/etc/init.d/sing-box"
singbox_local_init: "{{ singbox_local_temp_dir }}/init"

singbox_config: "/etc/sing-box/config.json"
singbox_local_config: "{{ singbox_local_files }}/config.json"

singbox_workdir: "/usr/share/sing-box"
