---
# install
teletrack_sources_local: ""
teletrack_bin_local: "{{ teletrack_sources_local }}/teletrack"
teletrack_config_local: "{{ teletrack_sources_local }}/config.json"

teletrack_install_dir: "/opt/teletrack"

teletrack_service_name: "teletrack"
teletrack_service: "/etc/systemd/system/{{ teletrack_service_name }}.service"