---
- name: "firewall: allow singbox"
  hosts: all
  become: true
  tasks:
    - name: "firewall: add, apply rules"
      block:
        - name: "Allow"
          ansible.builtin.include_role:
            name: firewall
            tasks_from: rules.yml
          vars:
            firewall_rule_name: "allow_singbox"
            firewall_rules: "{{ singbox_firewall_rules }}"

        - name: Apply
          ansible.builtin.include_role:
            name: firewall
            tasks_from: apply.yml
