---
- name: "firewall: allow HTTP"
  hosts: all
  become: true
  tasks:
    - name: "firewall: add, apply rules"
      block:
        - name: "Allow: 80, 443 TCP; 443 UDP"
          ansible.builtin.include_role:
            name: firewall
            tasks_from: rules.yml
          vars:
            firewall_rule_name: "allow_http"
            firewall_rules:
              - "add rule inet filter input tcp dport 80 accept"
              - "add rule inet filter input tcp dport 443 accept"
              - "add rule inet filter input udp dport 443 accept"
        - name: Apply
          ansible.builtin.include_role:
            name: firewall
            tasks_from: apply.yml
