---
# required vars: docker_dir; docker_group; docker_network

# general
singbox_dir: "{{ docker_dir }}/sing-box"
singbox_container_name: "sing_box"
singbox_certificates: ""

# install
singbox_image: "{{ singbox_dir }}/Dockerfile"
singbox_data: "{{ singbox_dir }}/data"
singbox_template_compose: "compose.yml.j2"
singbox_compose: "{{ singbox_dir }}/compose.yml"
singbox_reload_script: "{{ singbox_dir }}/reload.sh"

# deploy_config | deploy_config_mixed | deploy_config_mixed_wg (shadowing)
singbox_template_config: "mixed.json.j2"

# deploy_config_mixed_wg
singbox_template_config_wg: "mixed.wg.json.j2"

# deploy_config_mixed_wg (shadowing)
singbox_wg_config: "" # wireguard profile
# parsed by deploy_config_mixed_wg
singbox_private_key: ""
singbox_public_key: ""
singbox_mtu: ""
singbox_address_ipv4: ""
singbox_address_ipv6: ""
singbox_endpoint: ""
singbox_port: ""

# deploy_config
singbox_config: "{{ singbox_dir }}/config.json"

# mixed
singbox_listen_port: 1080
