---
# required vars: docker_dir; docker_group; docker_network

# Paths
singbox_dir: "{{ docker_dir }}/sing-box"
singbox_container_name: "sing_box"
singbox_certificates: ""
singbox_network: "singbox_network"

# install
singbox_image: "{{ singbox_dir }}/Dockerfile"
singbox_data: "{{ singbox_dir }}/data"
singbox_template_compose: "compose.yml.j2"
singbox_compose: "{{ singbox_dir }}/compose.yml"
singbox_reload_script: "{{ singbox_dir }}/reload.sh"

# Config templates
singbox_template_config: "mixed.json.j2"
singbox_template_config_wg: "mixed.wg.json.j2"

# WireGuard-related (deploy_config_mixed_wg)
singbox_wg_config: ""
singbox_private_key: ""
singbox_public_key: ""
singbox_mtu: ""
singbox_address_ipv4: ""
singbox_address_ipv6: ""
singbox_endpoint: ""
singbox_port: ""

singbox_config: "{{ singbox_dir }}/config.json"

# Listening
singbox_listen_port: 1080

# Resource limits
singbox_memory: "512m"
singbox_memory_reservation: "64m"
singbox_cpus: "1.0"

# download_locally
singbox_version: "1.14.0"
singbox_arch: "amd64-musl"
singbox_local_image: "local/sing-box-downloader:latest"
singbox_local_bin: "./downloaded/sing-box"

# deploy_config
singbox_openwrt: false

# install_openwrt
singbox_install_openwrt:
  local_temp: "./temp"
  workdir: "/usr/share/sing-box"
  bin: "/usr/local/bin/sing-box"
  local_bin: ""
  config: "/etc/sing-box/config.json"
  local_config: "{{ singbox_install_openwrt.local_temp }}/config.json"
  uci: "/etc/config/sing-box"
  local_uci: "{{ singbox_install_openwrt.local_temp }}/uci"
  init: "/etc/init.d/sing-box"
  local_init: "{{ singbox_install_openwrt.local_temp }}/init"
