---
- name: "include: install Docker"
  ansible.builtin.import_playbook: ../docker/install.yml

- name: "include: firewall allow HTTP"
  ansible.builtin.import_playbook: ../firewall/allow_http.yml

- name: "proxy: caddy-naive-sing-box"
  hosts: proxy
  become: true
  tasks:
    - name: "Export vars"
      block:
        - name: "lego: export vars"
          ansible.builtin.include_role:
            name: lego
            tasks_from: export_vars.yml

        - name: "caddy: export vars"
          ansible.builtin.include_role:
            name: caddy
            tasks_from: export_vars.yml

        - name: "sing-box: export vars"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: export_vars.yml

    - name: "Set vars"
      ansible.builtin.set_fact:
        lego_hooks:
          - path: "{{ caddy_reload_script }}"
            name: caddy.sh
        caddy_disable_insecure_upstreams_check: true
        caddy_upstream: "socks5://{{ singbox_container_name }}:{{ singbox_listen_port }}"
        caddy_certificates: "{{ lego_certificates_dir }}"

    - name: Ensure proxy network exists
      community.docker.docker_network:
        name: "{{ docker_network }}"
        driver: bridge
        state: present

    - name: "lego: install"
      ansible.builtin.include_role:
        name: lego
        tasks_from: install.yml

    - name: "caddy: install naive"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: install_naive.yml

    - name: "sing-box: install"
      block:
        - name: "install"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: install.yml

        - name: "deploy mixed config"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: deploy_config_mixed.yml

    - name: "lego: explicit start"
      ansible.builtin.include_role:
        name: lego
        tasks_from: explicit_start.yml
