---
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted

- name: Start Docker Compose
  ansible.builtin.command:
    cmd: >-
      docker compose
      -f {{ docker_compose_file }}
      up -d
      --build
    chdir: "{{ docker_dir }}"
