---
- name: "certbot: obtain"
  hosts: all
  become: true
  tasks:
    - name: nginx (no redirect HTTP)
      block:
        - name: Create base config
          vars:
            # If port 80 currently listened by nginx, certbot will fail
            # so disable for now.
            nginx_redirect_http: false
          ansible.builtin.include_role:
            name: nginx
            tasks_from: base.yml

        - name: Apply
          ansible.builtin.include_role:
            name: nginx
            tasks_from: apply.yml

    - name: "certbot: install, obtain, autorenew"
      block:
        - name: Install
          ansible.builtin.include_role:
            name: certbot
            tasks_from: install.yml

        - name: Install certbot-nginx
          ansible.builtin.include_role:
            name: certbot
            tasks_from: install_nginx.yml

        - name: Obtain
          ansible.builtin.include_role:
            name: certbot
            tasks_from: obtain.yml

        - name: Autorenew
          ansible.builtin.include_role:
            name: certbot
            tasks_from: autorenew.yml

    - name: nginx (redirect HTTP)
      block:
        - name: Create base config
          vars:
            nginx_redirect_http: true
          ansible.builtin.include_role:
            name: nginx
            tasks_from: base.yml

        - name: Apply
          ansible.builtin.include_role:
            name: nginx
            tasks_from: apply.yml
