---
- name: "singbox: install"
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install sing-box
      ansible.builtin.include_role:
        name: singbox
        tasks_from: install.yml
