---
- name: "sing-box: naive"
  hosts: singbox
  become: true
  vars:
    singbox_listen: "127.0.0.1:1080"
  tasks:
    - name: "sing-box: install"
      ansible.builtin.include_role:
        name: singbox
        tasks_from: install.yml

    - name: "firewall: apply rules"
      block:
        - name: "Allow: 80, 443 (TCP) for caddy"
          ansible.builtin.include_role:
            name: firewall
            tasks_from: rules.yml
          vars:
            firewall_rule_name: "allow_http"
            firewall_rules:
              - "add rule inet filter input tcp dport 80 accept"
              - "add rule inet filter input tcp dport 443 accept"

        - name: Apply
          ansible.builtin.include_role:
            name: firewall
            tasks_from: apply.yml

    - name: "caddy: install go, xcaddy, naive"
      block:
        - name: "golang: install"
          ansible.builtin.include_role:
            name: golang
            tasks_from: install.yml

        - name: "caddy: install xcaddy"
          ansible.builtin.include_role:
            name: caddy
            tasks_from: install_xcaddy.yml

        - name: "caddy: install naive"
          ansible.builtin.include_role:
            name: caddy
            tasks_from: install_naive.yml
          vars:
            caddy_naive_upstream_socks: "socks5://{{ singbox_listen }}"

    - name: "sing-box: apply mixed config"
      ansible.builtin.include_role:
        name: singbox
        tasks_from: mixed.yml
