---
- name: "caddy: deploy .conf files"
  hosts: all
  become: true
  tasks:
    - name: "caddy: generate, apply configs"
      block:
        - name: Generate
          ansible.builtin.include_role:
            name: caddy
            tasks_from: confd.yml

        - name: Apply
          ansible.builtin.include_role:
            name: caddy
            tasks_from: apply.yml
