---
- name: "include: install Docker"
  ansible.builtin.import_playbook: ../docker/install.yml

- name: "include: firewall allow HTTP"
  ansible.builtin.import_playbook: ../firewall/allow_http.yml

- name: "caddy: install"
  hosts: all
  become: true
  tasks:
    - name: Ensure proxy network exists
      community.docker.docker_network:
        name: "{{ docker_network }}"
        driver: bridge
        state: present

    - name: "lego: install"
      ansible.builtin.include_role:
        name: lego
        tasks_from: install.yml

    - name: "caddy: install naive"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: install_naive.yml

    - name: "sing-box: install"
      block:
        - name: "install"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: install.yml

        - name: "deploy config"
          ansible.builtin.include_role:
            name: singbox
            tasks_from: deploy_config.yml
