---
- name: "caddy: install"
  hosts: all
  become: true
  tasks:
    - name: Ensure proxy network exists
      community.docker.docker_network:
        name: "{{ docker_network }}"
        driver: bridge
        state: present

    - name: "caddy: install"
      ansible.builtin.include_role:
        name: caddy
        tasks_from: install.yml
