---
- name: "include: firewall allow Docker"
  ansible.builtin.import_playbook: ../firewall/allow_docker.yml

- name: "docker: install"
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: docker
        tasks_from: install.yml
