---
- name: "ansiblecfgs: reality-sing-box"
  hosts: all
  become: true
  handlers:
    - name: Restart sing-box
      ansible.builtin.systemd:
        name: sing-box
        state: restarted

  tasks:
    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download SagerNet GPG key
      ansible.builtin.get_url:
        url: https://sing-box.app/gpg.key
        dest: /etc/apt/keyrings/sagernet.asc
        mode: "0644"

    - name: Add SagerNet APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/sagernet.sources
        content: |
          Types: deb
          URIs: https://deb.sagernet.org/
          Suites: *
          Components: *
          Enabled: yes
          Signed-By: /etc/apt/keyrings/sagernet.asc
        mode: "0644"

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - sing-box
        state: present
        update_cache: yes
      register: apt_result
      until: apt_result is succeeded
      retries: 10
      delay: 15

    - name: Generate shortID
      ansible.builtin.command: sing-box generate rand --hex 8
      register: singbox_short_id

    - name: Notify shortID
      ansible.builtin.debug:
        msg: "ATTENTION! Your sing-box shortID is: {{ singbox_short_id.stdout }}. It needed for client."

    - name: Generate sing-box UUID
      ansible.builtin.command: sing-box generate uuid
      register: singbox_uuid

    - name: Notify UUID
      ansible.builtin.debug:
        msg: "ATTENTION! Your sing-box UUID is: {{ singbox_uuid.stdout }}. It needed for client."

    - name: Generate sing-box reality key pair
      ansible.builtin.command: sing-box generate reality-keypair
      register: singbox_keys

    - name: Extract sing-box reality keys
      ansible.builtin.set_fact:
        singbox_private_key_e: "{{ singbox_keys.stdout.split('PrivateKey: ')[1].split()[0] }}"
        singbox_public_key_e: "{{ singbox_keys.stdout.split('PublicKey: ')[1].split()[0] }}"

    - name: Notify public key
      ansible.builtin.debug:
        msg: "ATTENTION! Your reality public key is: {{ singbox_public_key_e }}. It needed for client."

    - name: Generate sing-box config
      ansible.builtin.template:
        src: sing-box.json.j2
        dest: /etc/sing-box/config.json
      vars:
        singbox_private_key: "{{ singbox_private_key_e }}"
      notify: Restart sing-box

    - name: Enable and start sing-box
      ansible.builtin.systemd:
        name: sing-box
        enabled: true
        state: started
