---
# required vars: docker_dir; docker_group

# lego
lego_dir: "{{ docker_dir }}/lego"
lego_storage: "{{ lego_dir }}/data/"
lego_certificates_dir: "{{ lego_storage }}/certificates"
lego_email: "foo@example.com"
lego_config: "{{ lego_dir }}/config.yml"
lego_cloudflare_api_token: ""
lego_cloudflare_env: "{{ lego_dir }}/cloudflare.env"
lego_runner: "{{ lego_dir }}/runner.sh"
lego_reload: "{{ lego_dir }}/reload.sh"
lego_reload_hooks:
  #- docker exec caddy caddy reload --config /etc/caddy/Caddyfile

# lego_domains:
#   - example.com
#   - "*.example.com"
