---
# deploy_files
routine_rsync_opts:
  - "--no-motd"
  - "--human-readable"
# routine_files:
#   - src: "files/frontend/dist/"
#     dest: "/var/www/frontend/"
#     owner: "www-data"
#     group: "www-data"
#     mode: "0755"
#     rsync_opts:
#       - "--exclude=*.map"
#       - "--exclude=.gitkeep"
