---
- name: Ensure local temp directory exists
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ singbox_install_openwrt.local_temp }}"
    state: directory
    mode: "0755"

- name: Render config locally
  delegate_to: localhost
  become: false
  ansible.builtin.template:
    src: "{{ singbox_template_config }}"
    dest: "{{ singbox_install_openwrt.local_config }}"

- name: Copy config
  delegate_to: localhost
  become: false
  ansible.builtin.shell:
    cmd: >
      scp -P {{ ansible_port }}
      "{{ singbox_install_openwrt.local_config }}"
      root@{{ ansible_host }}:"{{ singbox_install_openwrt.config }}"

- name: Restart sing-box service
  ansible.builtin.raw: service sing-box restart || true

- name: Remove local temp directory
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ singbox_install_openwrt.local_temp }}"
    state: absent
