---
- name: Deploy sing-box config
  ansible.builtin.template:
    src: "{{ singbox_template_config }}"
    dest: "{{ singbox_config }}"
    owner: "1000"
    group: "1000"
    mode: "0644"
  notify: Recreate sing-box
