---
# Export from roles to playbook
- name: Export variables
  ansible.builtin.set_fact:
    singbox_container_name: "{{ singbox_container_name }}"
    singbox_listen_port: "{{ singbox_listen_port }}"
    singbox_reload_script: "{{ singbox_reload_script }}"
