---
- name: Check if sing-box is already installed
  ansible.builtin.command: sing-box version
  register: singbox_current
  failed_when: false
  changed_when: false

# why sh script? cuz official repo hosted in AWS, blocked in Russia (38 KB block)
- name: Install / Update sing-box
  ansible.builtin.shell: |
    curl -fsSL https://sing-box.app/install.sh | sh -s -- --version {{ singbox_version }}
  args:
    executable: /bin/bash
  become: true
  when: >
    singbox_current.rc != 0 or
    (singbox_version not in (singbox_current.stdout | default('')))
  register: singbox_install_result
