---
- name: Create sing-box directory
  ansible.builtin.file:
    path: "{{ singbox_dir }}"
    state: directory
    group: "{{ docker_group }}"
    mode: "0755"

- name: Create sing-box data directory
  ansible.builtin.file:
    path: "{{ singbox_data }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"

- name: Copy sing-box Dockerfile
  ansible.builtin.copy:
    src: sing-box.Dockerfile
    dest: "{{ singbox_image }}"

- name: Render Compose file
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ singbox_compose }}"
    mode: "0644"

- include_tasks: deploy_config.yml

- include_tasks: restart.yml
