---
- name: Check if identity exists
  ansible.builtin.stat:
    path: "{{ singbox_identity_path }}"
  register: singbox_identity_stat

- name: Generate Identity
  when: not singbox_identity_stat.stat.exists
  block:
    - name: Ensure identity dir exists
      ansible.builtin.file:
        path: "{{ singbox_identity_path | dirname }}"
        state: directory
        mode: "0755"

    - name: Generate short ID
      ansible.builtin.command: sing-box generate rand --hex 8
      register: singbox_short_id
      changed_when: true

    - name: Generate UUID
      ansible.builtin.command: sing-box generate uuid
      register: singbox_uuid
      changed_when: true

    - name: Generate reality-keypair
      ansible.builtin.command: sing-box generate reality-keypair
      register: singbox_keys
      changed_when: true

    - name: Save identity
      ansible.builtin.copy:
        dest: "{{ singbox_identity_path }}"
        mode: "0600"
        content: |
          short_id: "{{ singbox_short_id.stdout | trim }}"
          uuid: "{{ singbox_uuid.stdout | trim }}"
          private_key: "{{ singbox_keys.stdout | regex_search('PrivateKey:\\s*(\\S+)', '\1') }}"
          public_key: "{{ singbox_keys.stdout | regex_search('PublicKey:\\s*(\\S+)', '\1') }}"
      register: identity_created

- name: Re-check if identity file exists
  ansible.builtin.stat:
    path: "{{ singbox_identity_path }}"
  register: singbox_identity_stat

- name: Load identity
  when:
    - singbox_identity_stat.stat.exists | default(false)
    - (singbox_identity_stat.stat.size | default(0)) > 0
  block:
    - name: Slurp identity file
      ansible.builtin.slurp:
        src: "{{ singbox_identity_path }}"
      register: singbox_identity_raw

    - name: Parse identity YAML
      ansible.builtin.set_fact:
        singbox_identity: "{{ singbox_identity_raw['content'] | b64decode | from_yaml }}"
