---
- name: Get sing_box container info
  community.docker.docker_container_info:
    name: "{{ singbox_container_name }}"
  register: singbox_container_info

- name: Ensure sing_box is running
  community.docker.docker_compose_v2:
    project_src: "{{ singbox_dir }}"
    files:
      - "{{ singbox_compose }}"
    state: present
    build: always
  when: >-
    not singbox_container_info.exists
    or singbox_container_info.container.State.Status != 'running'
