---
- name: Check if identity exists
  ansible.builtin.stat:
    path: "{{ singbox_identity_path }}"
  register: singbox_identity_stat

- name: Generate Identity
  when: not singbox_identity_stat.stat.exists
  block:
    - name: Ensure identity dir exists
      ansible.builtin.file:
        path: "{{ singbox_identity_path | dirname }}"
        state: directory
        mode: "0755"

    - name: Generate sing-box wg-keypair (server)
      ansible.builtin.command: sing-box generate wg-keypair
      register: singbox_server_keys
      changed_when: true

    - name: Generate sing-box wg-keypair (client)
      ansible.builtin.command: sing-box generate wg-keypair
      register: singbox_client_keys
      changed_when: true

    - name: Save identity
      ansible.builtin.copy:
        dest: "{{ singbox_identity_path }}"
        mode: "0600"
        content: |
          server_private_key: "{{ singbox_server_keys.stdout | regex_search('PrivateKey: ([A-Za-z0-9+/=]+)', '\1') }}"
          server_public_key: "{{ singbox_server_keys.stdout | regex_search('PublicKey: ([A-Za-z0-9+/=]+)', '\1') }}"
          client_private_key: "{{ singbox_client_keys.stdout | regex_search('PrivateKey: ([A-Za-z0-9+/=]+)', '\1') }}"
          client_public_key: "{{ singbox_client_keys.stdout | regex_search('PublicKey: ([A-Za-z0-9+/=]+)', '\1') }}"
        register: identity_created

- name: Load identity
  when:
    - singbox_identity_stat.stat.exists | default(false)
    - singbox_identity_stat.stat.size | default(0) > 0
  block:
    - name: Slurp identity file
      ansible.builtin.slurp:
        src: "{{ singbox_identity_path }}"
      register: singbox_identity_raw

    - name: Parse identity YAML
      ansible.builtin.set_fact:
        singbox_identity: "{{ singbox_identity_raw['content'] | b64decode | from_yaml }}"
