---
- name: Create xray_autoupdate helper script
  ansible.builtin.template:
    src: autoupdate.sh.j2
    dest: "{{ xray_autoupdate_script }}"
    owner: root
    group: root
    mode: "0755"

- name: Install xray_autoupdate systemd service
  ansible.builtin.template:
    src: autoupdate.service.j2
    dest: "/etc/systemd/system/xray_autoupdate.service"
    owner: root
    group: root
    mode: "0644"
  notify: systemd daemon-reload

- name: Install xray-update systemd timer
  ansible.builtin.template:
    src: autoupdate.timer.j2
    dest: "/etc/systemd/system/xray_autoupdate.timer"
    owner: root
    group: root
    mode: "0644"
  notify: systemd daemon-reload

- name: Enable and start xray_autoupdate timer
  ansible.builtin.systemd:
    name: "xray_autoupdate.timer"
    enabled: true
    state: started

- name: Trigger service immediately after enabling timer
  ansible.builtin.systemd:
    name: xray_autoupdate.service
    state: restarted