---
- name: Ensure local temp directory exists
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ xray_install_openwrt.local_temp }}"
    state: directory
    mode: "0755"

- name: Render config locally
  delegate_to: localhost
  become: false
  ansible.builtin.template:
    src: "{{ xray_template_config }}"
    dest: "{{ xray_install_openwrt.local_config }}"

- name: Copy config
  delegate_to: localhost
  become: false
  ansible.builtin.shell:
    cmd: >
      scp -P {{ ansible_port }}
      "{{ xray_install_openwrt.local_config }}"
      root@{{ ansible_host }}:"{{ xray_install_openwrt.config }}"

- name: Restart xray service
  ansible.builtin.raw: service xray restart || true

- name: Remove local temp directory
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ xray_install_openwrt.local_temp }}"
    state: absent
