---
- name: Validate required Xray variables
  assert:
    that:
      - xray_username is defined
      - xray_bin is defined
      - xray_config_dir is defined
    fail_msg: "xray_username, xray_bin and xray_config_dir must be defined"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Create xray system user
  user:
    name: "{{ xray_username }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: no
    state: present

- name: Install Xray
  shell: |
    bash -c "$(curl -fsSL https://github.com/XTLS/Xray-install/raw/main/install-release.sh)" @ install -u {{ xray_username }}
  args:
    creates: "{{ xray_bin }}"
    executable: /bin/bash

- name: Ensure config directory exists
  file:
    path: "{{ xray_config_dir }}"
    state: directory
    owner: "{{ xray_username }}"
    group: "{{ xray_username }}"
    mode: "0750"

- name: Ensure log directory exists
  file:
    path: "{{ xray_log_dir }}"
    state: directory
    owner: "{{ xray_username }}"
    group: "{{ xray_username }}"
    mode: "0750"

- name: Ensure systemd override directory exists
  file:
    path: "{{ xray_systemd_override_dir }}"
    state: directory
    mode: "0755"

- name: Generate systemd override for xray
  ansible.builtin.template:
    src: install_systemd.conf.j2
    dest: "{{ xray_systemd_override_dir }}/{{ xray_systemd_override_conf }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemd daemon-reload
    - Enable and start Xray
    - Restart xray
