---
- name: Rebuild teletrack
  community.docker.docker_compose_v2:
    project_src: "{{ teletrack_dir }}"
    files:
      - "{{ teletrack_compose }}"
    state: present
    build: always
    recreate: always

- name: Restart teletrack
  community.docker.docker_compose_v2:
    project_src: "{{ teletrack_dir }}"
    files:
      - "{{ teletrack_compose }}"
    state: restarted

- name: Recreate teletrack
  community.docker.docker_compose_v2:
    project_src: "{{ teletrack_dir }}"
    files:
      - "{{ teletrack_compose }}"
    state: present
    recreate: always
