all:
  hosts:
    myvps:
      ansible_host: 127.0.0.1
      ansible_user: root
      ansible_port: 22
      ansible_password: "123"
      # system/setup
      system_new_root_password: "qwerty"
      system_new_user_name: "onlymecanlogin"
      system_new_user_password: "zxcvbn"
      system_new_ssh_port: 61465
