---
- name: Render reload script
  ansible.builtin.template:
    src: reload.sh.j2
    dest: "{{ lego_reload }}"
    group: "{{ docker_group }}"
    mode: "0755"
  when: lego_reload is defined and lego_reload | length > 0
