---
- import_playbook: ../install-sing-box/playbook.yml
- import_playbook: ../generate-cert/playbook.yml
- name: "ansiblecfgs: tls-sing-box"
  hosts: all
  become: true
  tasks:
    - name: Generate sing-box UUID
      ansible.builtin.command: sing-box generate uuid
      register: singbox_uuid

    - name: Notify UUID
      ansible.builtin.debug:
        msg: "ATTENTION! Your sing-box UUID is: {{ singbox_uuid.stdout }}. It needed for client."

    - name: Generate sing-box config
      ansible.builtin.template:
        src: sing-box.json.j2
        dest: /etc/sing-box/config.json
      notify: Restart sing-box

    - name: Enable and start sing-box
      ansible.builtin.systemd:
        name: sing-box
        enabled: true
        state: started
  handlers:
    - name: Restart sing-box
      ansible.builtin.systemd:
        name: sing-box
        state: restarted
