---
- name: "ansiblecfgs: install-sing-box"
  hosts: all
  become: true
  tasks:
    - name: Ensure /etc/apt/keyrings exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Download SagerNet GPG key
      ansible.builtin.get_url:
        url: https://sing-box.app/gpg.key
        dest: /etc/apt/keyrings/sagernet.asc
        mode: "0644"

    - name: Add SagerNet APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/sagernet.sources
        content: |
          Types: deb
          URIs: https://deb.sagernet.org/
          Suites: *
          Components: *
          Enabled: yes
          Signed-By: /etc/apt/keyrings/sagernet.asc
        mode: "0644"

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - sing-box
        state: present
        update_cache: yes
      register: apt_result
      until: apt_result is succeeded
      retries: 10
      delay: 15