---
- import_playbook: ../routine/deploy_files.yml

- name: "xray: deploy geofiles"
  hosts: xray
  become: true
  tasks:
    - name: Restart Xray
      systemd:
        name: xray
        state: restarted
