---
# assumed that system/setup.yml manually executed before
- name: "Import: nginx (base)"
  ansible.builtin.import_playbook: ../nginx/base.yml

- name: "Import: certbot (obtain)"
  ansible.builtin.import_playbook: ../certbot/obtain.yml

- name: "Import: Xray XHTTP (SFY)"
  ansible.builtin.import_playbook: xhttp_sfy.yml

- name: "Import: Xray (deploy-geo)"
  ansible.builtin.import_playbook: deploy_geo.yml

- name: "Xray"
  hosts: xray
  become: true
  tasks:
