---
- name: Install rsync
  ansible.builtin.package:
    name: rsync
    state: present

- name: Allow {{ ansible_user }} to run rsync without password
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/ansible-rsync"
    create: yes
    mode: "0440"
    owner: root
    group: root
    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: /usr/bin/rsync"
    state: present
    validate: "visudo -cf %s"
  become: true

- name: Sync dirs
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    dest_port: "{{ ansible_port | int }}"
    mode: push
    rsync_opts: "{{ routine_rsync_opts + item.rsync_opts | default([]) }}"
    rsync_path: sudo rsync
    delete: "{{ item.delete | default(false) }}"
    checksum: "{{ item.checksum | default(false) }}"
    compress: "{{ item.compress | default(true) if ansible_fqdn != 'localhost' else false }}"
    recursive: yes
    archive: yes
  become: "{{ item.become | default(true) }}"
  loop: "{{ routine_files }}"
  loop_control:
    label: "{{ item.src }} - {{ item.dest }}"
  register: sync_result
  changed_when: sync_result.changed or sync_result.msg is search("files transferred")

- name: Set rights on directories (recursive)
  ansible.builtin.file:
    path: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0755') }}"
    state: directory
    recurse: yes
  loop: "{{ routine_files }}"
  when:
    - item.owner is defined or item.group is defined or item.mode is defined
    - item.is_directory | default(true)

- name: Set rights on individual files (no recurse)
  ansible.builtin.file:
    path: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('0644') }}"
    state: file
  loop: "{{ routine_files }}"
  when:
    - item.owner is defined or item.group is defined or item.mode is defined
    - not (item.is_directory | default(true))
