---
- name: Download UPX
  delegate_to: localhost
  become: false
  block:
    - name: Ensure upx_workdir exists
      file:
        path: "{{ upx_workdir }}"
        state: directory
        mode: "0755"

    - name: Download UPX tarball if not present
      get_url:
        url: "{{ upx_url }}"
        dest: "{{ upx_workdir }}/upx.tar.xz"
        mode: "0644"
        force: false

    - name: Extract UPX if binary does not exist
      unarchive:
        src: "{{ upx_workdir }}/upx.tar.xz"
        dest: "{{ upx_workdir }}"
        remote_src: true
        creates: "{{ upx_workdir }}/upx"

    - name: Find and move UPX binary to root of workdir
      find:
        paths: "{{ upx_workdir }}"
        patterns: "upx"
        file_type: file
        recurse: true
      register: upx_files

    - name: Move UPX binary to root of workdir
      command: mv "{{ item.path }}" "{{ upx_workdir }}/upx"
      loop: "{{ upx_files.files }}"
      when:
        - upx_files.files | length > 0
        - not (upx_workdir + '/upx') is exists

    - name: Ensure UPX binary is executable
      file:
        path: "{{ upx_workdir }}/upx"
        mode: "0755"
        state: file

    - name: Clean up unnecessary files in upx_workdir
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ lookup('fileglob', upx_workdir + '/*', wantlist=True) | difference([upx_workdir + '/upx']) }}"
