---
- name: Set docker_compose_file
  ansible.builtin.set_fact:
    docker_compose_file: "{{ docker_dir }}/caddy-naive-singbox.yml"

- name: Copy caddy-naive.html as index.html
  ansible.builtin.copy:
    src: html/caddy-naive.html
    dest: "{{ docker_caddy_file_server }}/index.html"

- name: Render Compose file
  ansible.builtin.template:
    src: compose/caddy-naive-singbox.yml.j2
    dest: "{{ docker_dir }}/caddy-naive-singbox.yml"
    mode: "0644"
  notify: Start Docker Compose
