- name: "openwrt: deploy sing-box config"
  hosts: openwrt
  gather_facts: false
  vars:
    singbox_config: "/etc/sing-box/config.json"
  tasks:
    - name: Ensure singbox_local_config is defined
      assert:
        that:
          - singbox_local_config is defined
          - singbox_local_config | length > 0
        fail_msg: "singbox_local_config must be defined"

    - name: Upload config
      delegate_to: localhost
      command: scp -o StrictHostKeyChecking=no -P {{ ansible_port }} {{ singbox_local_config }} {{ ansible_user }}@{{ ansible_host }}:{{ singbox_config }}

    - name: Restart sing-box
      raw: "/etc/init.d/sing-box restart"

    - name: Remove files if singbox_files_to_delete is defined
      raw: rm -f "{{ item.dest }}"
      loop: "{{ singbox_files_to_delete | default([]) }}"
      loop_control:
        label: "{{ item.dest }}"
      when: singbox_files_to_delete is defined
