# install
mihomo_version: "v1.19.20"
mihomo_arch: "linux-amd64-v3"
mihomo_download_url: "https://github.com/MetaCubeX/mihomo/releases/download/{{ mihomo_version }}/mihomo-{{ mihomo_arch }}-{{ mihomo_version }}.gz"

mihomo_bin_path: "/usr/local/bin/mihomo"
mihomo_config_dir: "/etc/mihomo"
mihomo_config_file: "config.yaml"

# (systemd)
mihomo_limit_nproc: 500
mihomo_limit_nofile: 1000000
